use_frameworks!

platform :ios, '13.0'

target 'GGAlicomGraphicAuthenticationSDK_Example' do
  pod 'GGAlicomGraphicAuthenticationSDK', :path => '../'

  target 'GGAlicomGraphicAuthenticationSDK_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
